# Generated by Django 3.0.6 on 2020-07-28 05:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200728_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='image',
            field=models.ImageField(blank=True, default='object_types/default.jpg', upload_to=api.models.PathAndRename('object_types')),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='instruction',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
