# Generated by Django 3.0.6 on 2020-08-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200728_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemodel',
            name='postprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinemodel',
            name='preprocess',
            field=models.BooleanField(default=False),
        ),
    ]
