# Generated by Django 3.0.6 on 2020-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200817_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
