# Generated by Django 3.0.6 on 2020-10-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='is_object_detection',
            field=models.BooleanField(default=False),
        ),
    ]
