# Generated by Django 3.0.6 on 2020-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_classifier_is_object_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='ibm_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
