# Generated by Django 2.0 on 2020-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_classifier_ibm_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
