# Generated by Django 2.0 on 2021-02-03 16:31

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='classes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='given_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='ibm_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IBM API KEY'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='is_object_detection',
            field=models.BooleanField(default=False, verbose_name='Is Object Detection'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='api.ObjectType', verbose_name='Object Type'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='offline_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='api.OfflineModel', verbose_name='Offline Model'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='projects.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.PathAndRename('contributions'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='is_helpful',
            field=models.BooleanField(default=False, verbose_name='Is Helpful'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.ObjectType', verbose_name='Object Type'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=api.models.PathAndRename('file'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to=api.models.PathAndRename('image'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='api.Image', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='object_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Object Type'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='pipeline_status',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Pipeline Status'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='result',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='retrained',
            field=models.BooleanField(default=False, verbose_name='Retrained'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='score',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='Tested'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_types', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='image',
            field=models.ImageField(blank=True, default='object_types/default.jpg', upload_to=api.models.PathAndRename('object_types'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='instruction',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_types', to='projects.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='wishlist',
            field=models.BooleanField(default=False, verbose_name='Wishlist'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_models', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='file',
            field=models.FileField(upload_to=api.models.PathAndRename('offline_models'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='model_format',
            field=models.CharField(max_length=50, verbose_name='Model Format'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='model_type',
            field=models.CharField(max_length=200, verbose_name='Model Type'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='offline_model_labels',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Offline Model Labels'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='postprocess',
            field=models.BooleanField(default=False, verbose_name='Postprocess'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='preprocess',
            field=models.BooleanField(default=False, verbose_name='Preprocess'),
        ),
        migrations.AlterField(
            model_name='offlinemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
