# Generated by Django 2.0 on 2021-04-06 08:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210203_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='countries',
            field=django_countries.fields.CountryField(default='', max_length=746, multiple=True),
        ),
    ]
