# Generated by Django 3.2 on 2021-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_objecttype_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='ibm_service_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IBM Service URL'),
        ),
    ]
