# Generated by Django 3.0.6 on 2020-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200407_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('engineer', 'Engineer'), ('government', 'Government'), ('project_admin', 'Project Admin'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
