# Generated by Django 3.0.6 on 2020-11-13 06:46

import crowdsource.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crowdsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=crowdsource.models.PathAndRename('crowdsource'))),
                ('object_type', models.CharField(default='other', max_length=200)),
                ('image_type', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed')], default='raw', max_length=50)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crowdsources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
