# Generated by Django 2.0 on 2021-02-03 16:31

import crowdsource.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crowdsources', to=settings.AUTH_USER_MODEL, verbose_name='Crowdsources'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='file',
            field=models.ImageField(upload_to=crowdsource.models.PathAndRename('crowdsource'), verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='image_type',
            field=models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed')], default='raw', max_length=50, verbose_name='Image Type'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='object_type',
            field=models.CharField(default='other', max_length=200, verbose_name='Object Type'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Username'),
        ),
    ]
