# Generated by Django 3.2.4 on 2021-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0004_delete_imagesharefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageshare',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Remarks'),
        ),
    ]
